[package]
name = "passrs"
version = "0.0.0"
authors = ["Cole Helbling <cole.e.helbling@outlook.com>"]
edition = "2018"
build = "build.rs"
publish = false

[dependencies]
data-encoding = "2.1"
failure = "0.1"
git2 = "0.11"
gpgme = "0.9"
rand = "0.7"
ring = "0.16"
# structopt = "0.3"
structopt = { git = "https://github.com/TeXitoi/structopt" }
termion = "1.5"
tui = "0.8"
walkdir = "2.2"
zeroize = "1.1"
once_cell = "1.2"

# thiserror = "1.0"
# anyhow = "1.0"

atty = "0.2"
grep-printer = "0.1"
grep-regex = "0.1"
grep-searcher = "0.1"
termcolor = "1.0"

fuzz-search = { version = "0.1", optional = true }
qrcode = { version = "0.11", default-features = false, features = ["svg"], optional = true }
regex = { version = "1.3", default-features = false, features = ["std"], optional = true }

[build-dependencies]
rustc_tools_util = "0.2"

[features]
default = ["otp", "fuzzy"]

fuzzy = ["fuzz-search"]
otp = ["regex", "qrcode"]
