[package]
name = "passrs"
version = "0.1.0"
authors = ["Cole Helbling <cole.e.helbling@outlook.com>"]
edition = "2018"
build = "build.rs"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7"
envmnt = "0.7"
git2 = "0.11"
hex = "0.4"
rand = "0.7"
ring = "0.16"
structopt = "0.3"
rpassword = "4.0"
rprompt = "1.0"
lazy_static = "1.4"
failure = "0.1"
walkdir = "2.2"
regex = { version = "1.3", default-features = false, features = ["std"] }

tui = { version = "0.8", optional = true }
termion = { version = "1.5", optional = true }
gpgme = { version = "0.9", optional = true }
otpauth = { version = "0.4", optional = true }

[build-dependencies]
rustc_tools_util = "0.2"

[features]
default = ["gpg", "otp", "ui"]
gpg = ["gpgme"]
otp = ["otpauth"]
ui = ["tui", "termion"]
