[package]
name = "passrs"
version = "0.0.0"
authors = ["Cole Helbling <cole.e.helbling@outlook.com>"]
edition = "2018"
build = "build.rs"
publish = false

[dependencies]
anyhow = "1.0"
data-encoding = "2.1"
git2 = { version = "0.11", default-features = false }
gpgme = "0.9"
grep-printer = { version = "0.1", default-features = false }
grep-regex = "0.1"
grep-searcher = "0.1"
once_cell = "1.2"
rand = "0.7"
ring = { version = "0.16", default-features = false }
# structopt = "0.3"
structopt = { git = "https://github.com/TeXitoi/structopt", default-features = false, features = ["suggestions", "color"] }
termcolor = "1.0"
termion = "1.5"
thiserror = "1.0"
tui = "0.8"
walkdir = "2.2"
zeroize = "1.1"

fuzz-search = { version = "0.1", optional = true }
qrcode = { version = "0.11", default-features = false, features = ["svg"], optional = true }
regex = { version = "1.3", default-features = false, optional = true }

[build-dependencies]
rustc_tools_util = "0.2"

[features]
default = ["otp", "fuzzy"]

fuzzy = ["fuzz-search"]
otp = ["regex", "qrcode"]

# [profile.release]
# debug = true
