name: CI

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
        components: rustfmt
    - name: Check rustfmt
      run: cargo +nightly fmt -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: beta
          components: clippy
      - name: Install GPG libs
        run: sudo apt-get install libgpg-error-dev libgpgme-dev
      - name: Check clippy
        run: cargo +beta clippy --all-features

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install GPG libs
      run: sudo apt-get install libgpg-error-dev libgpgme-dev
    - name: Run build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      env:
        PASSWORD_STORE_DIR: ${{ github.workspace }}/tests/test_repo
