name: CI

on:
  pull_request:
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/ci.yml'
  push:
    branches: [master]
    paths:
      - '**.rs'
      - '**.toml'
      - '.github/workflows/ci.yml'
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
        components: rustfmt
    - name: Check rustfmt
      run: cargo +nightly fmt -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
          components: clippy
      - name: Install GPG libs
        run: sudo apt-get install libgpg-error-dev libgpgme-dev
      - name: Check clippy
        run: cargo +nightly clippy --all-features -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v8
      - name: Run tests
        run: nix-build -E 'import ./default.nix { doCheck = true; release = false; }'
        env:
          RUST_BACKTRACE: 1
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0"
          # PASSWORD_STORE_DIR: ${{ github.workspace }}/tests/test_repo

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v8
      - name: Run build
        run: nix-build
        env:
          RUST_BACKTRACE: 1
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-C debuginfo=0"
