name: CI

on:
  pull_request:
  push:
    branches: [master]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly
        components: rustfmt
    - name: Check nightly rustfmt
      run: cargo +nightly fmt -- --check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly
          components: clippy
      - name: Install GPG libs
        run: sudo apt-get install libgpg-error-dev libgpgme-dev
      - name: Check nightly clippy
        run: cargo +nightly clippy --all-features -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v10
        with:
            skip_adding_nixpkgs_channel: true
            install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20200820_4d77513/install
      - run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
      - name: Run tests
        run: nix build .#test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v10
        with:
            skip_adding_nixpkgs_channel: true
            install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-3.0pre20200820_4d77513/install
      - run: echo "experimental-features = nix-command flakes" | sudo tee -a /etc/nix/nix.conf
      - name: Run build
        run: nix build
